In [1]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [2]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [6]:
df =pd.read_csv("/content/IMDB Dataset.csv",on_bad_lines='skip')

In [7]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
text = df['review']
text.head()

0    One of the other reviewers has mentioned that ...
1    A wonderful little production. <br /><br />The...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
Name: review, dtype: object

In [9]:
text = text.str.lower()

print(text.head())

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. <br /><br />the...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [10]:
text = text.apply(word_tokenize)

print(text.head())

0    [one, of, the, other, reviewers, has, mentione...
1    [a, wonderful, little, production, ., <, br, /...
2    [i, thought, this, was, a, wonderful, way, to,...
3    [basically, there, 's, a, family, where, a, li...
4    [petter, mattei, 's, ``, love, in, the, time, ...
Name: review, dtype: object

In [11]:
stopwords = set(stopwords.words('english'))

In [13]:
cleaned_text = []

for words in text:
    result = []

    for word in words:
        if word not in stopwords:
            result.append(word)

    cleaned_text.append(result)

print(cleaned_text[:5])

[['one', 'reviewers', 'mentioned', 'watching', '1', 'oz', 'episode', "'ll", 'hooked', '.', 'right', ',', 'exactly', 'happened', 'me.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'first', 'thing', 'struck', 'oz', 'brutality', 'unflinching', 'scenes', 'violence', ',', 'set', 'right', 'word', 'go', '.', 'trust', ',', 'show', 'faint', 'hearted', 'timid', '.', 'show', 'pulls', 'punches', 'regards', 'drugs', ',', 'sex', 'violence', '.', 'hardcore', ',', 'classic', 'use', 'word.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'called', 'oz', 'nickname', 'given', 'oswald', 'maximum', 'security', 'state', 'penitentary', '.', 'focuses', 'mainly', 'emerald', 'city', ',', 'experimental', 'section', 'prison', 'cells', 'glass', 'fronts', 'face', 'inwards', ',', 'privacy', 'high', 'agenda', '.', 'em', 'city', 'home', 'many', '..', 'aryans', ',', 'muslims', ',', 'gangstas', ',', 'latinos', ',', 'christians', ',', 'italians', ',', 'irish', '....', 'scuffles', ',', 'death', 'stares', ',', 'dodgy', 'dealings', 'shady', 'agreements', 'never', 'far', 'away.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'would', 'say', 'main', 'appeal', 'show', 'due', 'fact', 'goes', 'shows', 'would', "n't", 'dare', '.', 'forget', 'pretty', 'pictures', 'painted', 'mainstream', 'audiences', ',', 'forget', 'charm', ',', 'forget', 'romance', '...', 'oz', "n't", 'mess', 'around', '.', 'first', 'episode', 'ever', 'saw', 'struck', 'nasty', 'surreal', ',', 'could', "n't", 'say', 'ready', ',', 'watched', ',', 'developed', 'taste', 'oz', ',', 'got', 'accustomed', 'high', 'levels', 'graphic', 'violence', '.', 'violence', ',', 'injustice', '(', 'crooked', 'guards', "'ll", 'sold', 'nickel', ',', 'inmates', "'ll", 'kill', 'order', 'get', 'away', ',', 'well', 'mannered', ',', 'middle', 'class', 'inmates', 'turned', 'prison', 'bitches', 'due', 'lack', 'street', 'skills', 'prison', 'experience', ')', 'watching', 'oz', ',', 'may', 'become', 'comfortable', 'uncomfortable', 'viewing', '....', 'thats', 'get', 'touch', 'darker', 'side', '.'], ['wonderful', 'little', 'production', '.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'filming', 'technique', 'unassuming-', 'old-time-bbc', 'fashion', 'gives', 'comforting', ',', 'sometimes', 'discomforting', ',', 'sense', 'realism', 'entire', 'piece', '.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'actors', 'extremely', 'well', 'chosen-', 'michael', 'sheen', '``', 'got', 'polari', "''", 'voices', 'pat', '!', 'truly', 'see', 'seamless', 'editing', 'guided', 'references', 'williams', "'", 'diary', 'entries', ',', 'well', 'worth', 'watching', 'terrificly', 'written', 'performed', 'piece', '.', 'masterful', 'production', 'one', 'great', 'master', "'s", 'comedy', 'life', '.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'realism', 'really', 'comes', 'home', 'little', 'things', ':', 'fantasy', 'guard', ',', 'rather', 'use', 'traditional', "'dream", "'", 'techniques', 'remains', 'solid', 'disappears', '.', 'plays', 'knowledge', 'senses', ',', 'particularly', 'scenes', 'concerning', 'orton', 'halliwell', 'sets', '(', 'particularly', 'flat', 'halliwell', "'s", 'murals', 'decorating', 'every', 'surface', ')', 'terribly', 'well', 'done', '.'], ['thought', 'wonderful', 'way', 'spend', 'time', 'hot', 'summer', 'weekend', ',', 'sitting', 'air', 'conditioned', 'theater', 'watching', 'light-hearted', 'comedy', '.', 'plot', 'simplistic', ',', 'dialogue', 'witty', 'characters', 'likable', '(', 'even', 'well', 'bread', 'suspected', 'serial', 'killer', ')', '.', 'may', 'disappointed', 'realize', 'match', 'point', '2', ':', 'risk', 'addiction', ',', 'thought', 'proof', 'woody', 'allen', 'still', 'fully', 'control', 'style', 'many', 'us', 'grown', 'love.', '<', 'br', '/', '>', '<', 'br', '/', '>', "'d", 'laughed', 'one', 'woody', "'s", 'comedies', 'years', '(', 'dare', 'say', 'decade', '?', ')', '.', "'ve", 'never', 'impressed', 'scarlet', 'johanson', ',', 'managed', 'tone', '``', 'sexy', "''", 'image', 'jumped', 'right', 'average', ',', 'spirited', 'young', 'woman.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'may', 'crown', 'jewel', 'career', ',', 'wittier', '``', 'devil', 'wears', 'prada', "''", 'interesting', '``', 'superman', "''", 'great', 'comedy', 'go', 'see', 'friends', '.'], ['basically', "'s", 'family', 'little', 'boy', '(', 'jake', ')', 'thinks', "'s", 'zombie', 'closet', '&', 'parents', 'fighting', 'time.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'movie', 'slower', 'soap', 'opera', '...', 'suddenly', ',', 'jake', 'decides', 'become', 'rambo', 'kill', 'zombie.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'ok', ',', 'first', "'re", 'going', 'make', 'film', 'must', 'decide', 'thriller', 'drama', '!', 'drama', 'movie', 'watchable', '.', 'parents', 'divorcing', '&', 'arguing', 'like', 'real', 'life', '.', 'jake', 'closet', 'totally', 'ruins', 'film', '!', 'expected', 'see', 'boogeyman', 'similar', 'movie', ',', 'instead', 'watched', 'drama', 'meaningless', 'thriller', 'spots.', '<', 'br', '/', '>', '<', 'br', '/', '>', '3', '10', 'well', 'playing', 'parents', '&', 'descent', 'dialogs', '.', 'shots', 'jake', ':', 'ignore', '.'], ['petter', 'mattei', "'s", '``', 'love', 'time', 'money', "''", 'visually', 'stunning', 'film', 'watch', '.', 'mr.', 'mattei', 'offers', 'us', 'vivid', 'portrait', 'human', 'relations', '.', 'movie', 'seems', 'telling', 'us', 'money', ',', 'power', 'success', 'people', 'different', 'situations', 'encounter', '.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'variation', 'arthur', 'schnitzler', "'s", 'play', 'theme', ',', 'director', 'transfers', 'action', 'present', 'time', 'new', 'york', 'different', 'characters', 'meet', 'connect', '.', 'one', 'connected', 'one', 'way', ',', 'another', 'next', 'person', ',', 'one', 'seems', 'know', 'previous', 'point', 'contact', '.', 'stylishly', ',', 'film', 'sophisticated', 'luxurious', 'look', '.', 'taken', 'see', 'people', 'live', 'world', 'live', 'habitat.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'thing', 'one', 'gets', 'souls', 'picture', 'different', 'stages', 'loneliness', 'one', 'inhabits', '.', 'big', 'city', 'exactly', 'best', 'place', 'human', 'relations', 'find', 'sincere', 'fulfillment', ',', 'one', 'discerns', 'case', 'people', 'encounter.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'acting', 'good', 'mr.', 'mattei', "'s", 'direction', '.', 'steve', 'buscemi', ',', 'rosario', 'dawson', ',', 'carol', 'kane', ',', 'michael', 'imperioli', ',', 'adrian', 'grenier', ',', 'rest', 'talented', 'cast', ',', 'make', 'characters', 'come', 'alive.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'wish', 'mr.', 'mattei', 'good', 'luck', 'await', 'anxiously', 'next', 'work', '.']]

In [14]:
stemmer = PorterStemmer()

stemmed_text = []

for words in cleaned_text:
    result = []

    for word in words:
        stem = stemmer.stem(word)
        result.append(stem)

    stemmed_text.append(result)

print(stemmed_text[:5])

[['one', 'review', 'mention', 'watch', '1', 'oz', 'episod', "'ll", 'hook', '.', 'right', ',', 'exactli', 'happen', 'me.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'first', 'thing', 'struck', 'oz', 'brutal', 'unflinch', 'scene', 'violenc', ',', 'set', 'right', 'word', 'go', '.', 'trust', ',', 'show', 'faint', 'heart', 'timid', '.', 'show', 'pull', 'punch', 'regard', 'drug', ',', 'sex', 'violenc', '.', 'hardcor', ',', 'classic', 'use', 'word.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'call', 'oz', 'nicknam', 'given', 'oswald', 'maximum', 'secur', 'state', 'penitentari', '.', 'focus', 'mainli', 'emerald', 'citi', ',', 'experiment', 'section', 'prison', 'cell', 'glass', 'front', 'face', 'inward', ',', 'privaci', 'high', 'agenda', '.', 'em', 'citi', 'home', 'mani', '..', 'aryan', ',', 'muslim', ',', 'gangsta', ',', 'latino', ',', 'christian', ',', 'italian', ',', 'irish', '....', 'scuffl', ',', 'death', 'stare', ',', 'dodgi', 'deal', 'shadi', 'agreement', 'never', 'far', 'away.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'would', 'say', 'main', 'appeal', 'show', 'due', 'fact', 'goe', 'show', 'would', "n't", 'dare', '.', 'forget', 'pretti', 'pictur', 'paint', 'mainstream', 'audienc', ',', 'forget', 'charm', ',', 'forget', 'romanc', '...', 'oz', "n't", 'mess', 'around', '.', 'first', 'episod', 'ever', 'saw', 'struck', 'nasti', 'surreal', ',', 'could', "n't", 'say', 'readi', ',', 'watch', ',', 'develop', 'tast', 'oz', ',', 'got', 'accustom', 'high', 'level', 'graphic', 'violenc', '.', 'violenc', ',', 'injustic', '(', 'crook', 'guard', "'ll", 'sold', 'nickel', ',', 'inmat', "'ll", 'kill', 'order', 'get', 'away', ',', 'well', 'manner', ',', 'middl', 'class', 'inmat', 'turn', 'prison', 'bitch', 'due', 'lack', 'street', 'skill', 'prison', 'experi', ')', 'watch', 'oz', ',', 'may', 'becom', 'comfort', 'uncomfort', 'view', '....', 'that', 'get', 'touch', 'darker', 'side', '.'], ['wonder', 'littl', 'product', '.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'film', 'techniqu', 'unassuming-', 'old-time-bbc', 'fashion', 'give', 'comfort', ',', 'sometim', 'discomfort', ',', 'sens', 'realism', 'entir', 'piec', '.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'actor', 'extrem', 'well', 'chosen-', 'michael', 'sheen', '``', 'got', 'polari', "''", 'voic', 'pat', '!', 'truli', 'see', 'seamless', 'edit', 'guid', 'refer', 'william', "'", 'diari', 'entri', ',', 'well', 'worth', 'watch', 'terrificli', 'written', 'perform', 'piec', '.', 'master', 'product', 'one', 'great', 'master', "'s", 'comedi', 'life', '.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'realism', 'realli', 'come', 'home', 'littl', 'thing', ':', 'fantasi', 'guard', ',', 'rather', 'use', 'tradit', "'dream", "'", 'techniqu', 'remain', 'solid', 'disappear', '.', 'play', 'knowledg', 'sens', ',', 'particularli', 'scene', 'concern', 'orton', 'halliwel', 'set', '(', 'particularli', 'flat', 'halliwel', "'s", 'mural', 'decor', 'everi', 'surfac', ')', 'terribl', 'well', 'done', '.'], ['thought', 'wonder', 'way', 'spend', 'time', 'hot', 'summer', 'weekend', ',', 'sit', 'air', 'condit', 'theater', 'watch', 'light-heart', 'comedi', '.', 'plot', 'simplist', ',', 'dialogu', 'witti', 'charact', 'likabl', '(', 'even', 'well', 'bread', 'suspect', 'serial', 'killer', ')', '.', 'may', 'disappoint', 'realiz', 'match', 'point', '2', ':', 'risk', 'addict', ',', 'thought', 'proof', 'woodi', 'allen', 'still', 'fulli', 'control', 'style', 'mani', 'us', 'grown', 'love.', '<', 'br', '/', '>', '<', 'br', '/', '>', "'d", 'laugh', 'one', 'woodi', "'s", 'comedi', 'year', '(', 'dare', 'say', 'decad', '?', ')', '.', "'ve", 'never', 'impress', 'scarlet', 'johanson', ',', 'manag', 'tone', '``', 'sexi', "''", 'imag', 'jump', 'right', 'averag', ',', 'spirit', 'young', 'woman.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'may', 'crown', 'jewel', 'career', ',', 'wittier', '``', 'devil', 'wear', 'prada', "''", 'interest', '``', 'superman', "''", 'great', 'comedi', 'go', 'see', 'friend', '.'], ['basic', "'s", 'famili', 'littl', 'boy', '(', 'jake', ')', 'think', "'s", 'zombi', 'closet', '&', 'parent', 'fight', 'time.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'movi', 'slower', 'soap', 'opera', '...', 'suddenli', ',', 'jake', 'decid', 'becom', 'rambo', 'kill', 'zombie.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'ok', ',', 'first', "'re", 'go', 'make', 'film', 'must', 'decid', 'thriller', 'drama', '!', 'drama', 'movi', 'watchabl', '.', 'parent', 'divorc', '&', 'argu', 'like', 'real', 'life', '.', 'jake', 'closet', 'total', 'ruin', 'film', '!', 'expect', 'see', 'boogeyman', 'similar', 'movi', ',', 'instead', 'watch', 'drama', 'meaningless', 'thriller', 'spots.', '<', 'br', '/', '>', '<', 'br', '/', '>', '3', '10', 'well', 'play', 'parent', '&', 'descent', 'dialog', '.', 'shot', 'jake', ':', 'ignor', '.'], ['petter', 'mattei', "'s", '``', 'love', 'time', 'money', "''", 'visual', 'stun', 'film', 'watch', '.', 'mr.', 'mattei', 'offer', 'us', 'vivid', 'portrait', 'human', 'relat', '.', 'movi', 'seem', 'tell', 'us', 'money', ',', 'power', 'success', 'peopl', 'differ', 'situat', 'encount', '.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'variat', 'arthur', 'schnitzler', "'s", 'play', 'theme', ',', 'director', 'transfer', 'action', 'present', 'time', 'new', 'york', 'differ', 'charact', 'meet', 'connect', '.', 'one', 'connect', 'one', 'way', ',', 'anoth', 'next', 'person', ',', 'one', 'seem', 'know', 'previou', 'point', 'contact', '.', 'stylishli', ',', 'film', 'sophist', 'luxuri', 'look', '.', 'taken', 'see', 'peopl', 'live', 'world', 'live', 'habitat.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'thing', 'one', 'get', 'soul', 'pictur', 'differ', 'stage', 'loneli', 'one', 'inhabit', '.', 'big', 'citi', 'exactli', 'best', 'place', 'human', 'relat', 'find', 'sincer', 'fulfil', ',', 'one', 'discern', 'case', 'peopl', 'encounter.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'act', 'good', 'mr.', 'mattei', "'s", 'direct', '.', 'steve', 'buscemi', ',', 'rosario', 'dawson', ',', 'carol', 'kane', ',', 'michael', 'imperioli', ',', 'adrian', 'grenier', ',', 'rest', 'talent', 'cast', ',', 'make', 'charact', 'come', 'alive.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'wish', 'mr.', 'mattei', 'good', 'luck', 'await', 'anxious', 'next', 'work', '.']]

In [18]:
final_text = []

for words in stemmed_text:
    sentence = ' '.join(words)
    final_text.append(sentence)

In [19]:
df['stemmed_review'] = final_text

In [20]:
print("Original Reviews:")
df['review'].head(5)

Original Reviews:

0    One of the other reviewers has mentioned that ...
1    A wonderful little production. <br /><br />The...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
Name: review, dtype: object

In [21]:
print("\nStemmed Reviews:")
df['stemmed_review'].head(5)

Stemmed Reviews:

0    one review mention watch 1 oz episod 'll hook ...
1    wonder littl product . < br / > < br / > film ...
2    thought wonder way spend time hot summer weeke...
3    basic 's famili littl boy ( jake ) think 's zo...
4    petter mattei 's `` love time money '' visual ...
Name: stemmed_review, dtype: object